QEMU_PROG_VIDEZZO=qemu-videzzo-$(TARGET_NAME)$(EXESUF)

videzzo-obj-y   += tests/qtest/libqtest.o
videzzo-obj-y   += $(libqos-obj-y)
videzzo-obj-y   += tests/qtest/videzzo/less_crashes_wrappers.o
videzzo-obj-y   += tests/qtest/videzzo/videzzo_qemu.o

VIDEZZO_LDFLAGS += -lvncclient -L$(SRC_PATH)/tests/qtest/videzzo -lvidezzo -Wl,-wrap,abort
